---
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DEFAULT_WORKSPACE=/workspace
    volumes:
      - ./config:/config
      - ./files:/workspace
    ports:
      - 8443:8443
    restart: unless-stopped
  FIT-E:
    image: oven/bun
    container_name: FIT-E
    volumes:
      - ./:/home/bun/app
    ports:
      - 3000:3000
    entrypoint: bun run index.ts
    restart: unless-stopped